### PR TITLE
Add nodelist flag to srun

### PR DESCRIPTION
**Pull request by guyueh1**
This change adds a nodelist flag to conf/cluster/bcm.yaml. The nodelist flag, if specified, will be written to sbatch script. This is useful for clusters where specifying partition is broken and specifying nodelist is needed instead.

### CODE REVIEW

**Comment by guyueh1** [comment]
@thomasdhc please review

**Comment by thomasdhc** [comment]
@guyueh1 Running tests now

**Comment by guyueh1** [comment]
@thomasdhc could you test again, thanks

**Comment by guyueh1** [comment]
@thomasdhc please review & test

**Review by thomasdhc — APPROVED** [review]
LGTM

**Comment by guyueh1** [comment]
Fix utest, making bcm utest consistent with `conf/cluster/bcm.yaml`.
Pls restart utest @thomasdhc

**Pull request merged**
