### PR TITLE
Add --cuda_graph_trace flag to the generated nsys ccommand

### PR DESCRIPTION
**Pull request by guyueh1**
This PR adds `--cuda-graph-trace=node` as an argument of the generated nsys profile command. When the workload is not using cuda graph, this flag has no impact on workload. When the workload uses cuda graph, this flag gives nsys the visibility of kernels within a cuda graph.

### CODE REVIEW

**Comment by guyueh1** [comment]
@thomasdhc could you review

**Comment by guyueh1** [comment]
@thomasdhc could you sign off ci for this PR

**Review by thomasdhc — APPROVED** [review]
LGTM

**Comment by thomasdhc** [comment]
Could you address the code style, let's merge it in after

**Comment by guyueh1** [comment]
> Could you address the code style, let's merge it in after

Done

**Pull request merged**
